Repository Cloud-Scythe-Labs/nix-watch, pull requests merged in 2024-08, with the labels that each got.

#6 Pass shell args to final command
  flake.nix
  nix-watch.nix
Labels: enhancement

#8 Add `nix-watch` lock file
  README.md
  flake.nix
  nix-watch.nix
Labels: bug, enhancement, darwin

#11 Add support for `NIX_WATCH_COMMAND` environment variable
  nix-watch.nix
Labels: enhancement

#12 Add support for debug env variable
  nix-watch.nix
Labels: enhancement

#13 Add support for `clear` env variable
  nix-watch.nix
Labels: enhancement

#14 Add support for `ignore-nothing` env variable
  nix-watch.nix
Labels: enhancement

#15 Add support for `no-restart` env variable
  nix-watch.nix
Labels: enhancement

#16 Add support for `postpone` env variable
  nix-watch.nix
Labels: enhancement

#17 Enable flake CI workflow checks
  .github/workflows/ci.yml
Labels: workflow

#20 Add `NIX_WATCH_SHELL_ARGS` env var
  nix-watch.nix
Labels: enhancement

#23 Add `NIX_WATCH_PRINT_BUILD_LOGS` env var
  nix-watch.nix
Labels: enhancement

#22 Add `NIX_WATCH_IGNORE_PATTERNS` env var
  nix-watch.nix
Labels: enhancement

#24 Add `bats` bash testing suite
  .github/workflows/ci.yml
  .gitignore
  flake.nix
  nix-watch.nix
  tests/default.nix
  tests/exec.nix
  tests/help.nix
  tests/ignore.nix
  tests/no-restart.nix
  tests/postpone.nix
  tests/shell-args.nix
  tests/shutdown.nix
  tests/test_utils.nix
  tests/workdir.nix
Labels: enhancement

#30 Consolidate tests into a nix store directory
  flake.nix
  tests/default.nix
  tests/exec.nix
  tests/help.nix
  tests/ignore.nix
  tests/no-restart.nix
  tests/postpone.nix
  tests/shell-args.nix
  tests/shutdown.nix
  tests/workdir.nix
Labels: enhancement

#31 Update `--help` output for `README`
  README.md
  nix-watch.nix
Labels: documentation
